helm:
  parameters:
  - name: guestbook.image.name
    value: gcr.io/heptio-images/ks-guestbook-demo
    forcestring: true
  - name: guestbook.image.tag
    value: "0.2"
    forcestring: true
  - name: nginx.image.name
    value: nginx
    forcestring: true
  - name: nginx.image.tag
    value: 1.19.10
    forcestring: true
  - name: chrome.image.name
    value: nginx
    forcestring: true
  - name: chrome.image.tag
    value: 1.24.0
    forcestring: true
