helm:
  parameters:
  - name: nginx.image.name
    value: nginx
    forcestring: true
  - name: nginx.image.tag
    value: 1.24.0
    forcestring: true
  - name: guestbook.image.name
    value: elvisfoxit/ks-guestbook-demo
    forcestring: true
  - name: guestbook.image.tag
    value: 0.2-prod
    forcestring: true
  - name: image.name
    value: nginx
    forcestring: true
  - name: chrome.image.name
    value: nginx
    forcestring: true
  - name: image.tag
    value: 1.23.4
    forcestring: true
