helm:
  parameters:
  - name: guestbook.image.name
    value: gcr.io/heptio-images/ks-guestbook-demo
    forcestring: true
  - name: guestbook.image.tag
    value: "0.1"
    forcestring: true
  - name: nginx.image.name
    value: nginx
    forcestring: true
  - name: nginx.image.tag
    value: 1.21.0
    forcestring: true
  - name: chrome.image.name
    value: nginx
    forcestring: true
  - name: chrome.image.tag
    value: "1.20"
    forcestring: true
