apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: "{{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}"
        name: nginx
