helm:
  parameters:
  - name: alpha.image
    value: gcr.io/heptio-images/ks-guestbook-demo
    forcestring: true
  - name: alpha.tag
    value: "0.2"
    forcestring: true
  - name: beta.image
    value: bguruprasad/ngnix-print-hostname
    forcestring: true
  - name: beta.tag
    value: 0.7-prod
    forcestring: true
